version: '3.1'

services: 
  ghost:
    ports:
      - "80:2368"
    env_file:
      - ./ghost-variables.env
    environment:
      NODE_ENV: production
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - ./ghost-variables.env
    networks:
      - ghost_net
    volumes: 
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: