version: '3.1'

services: 
  ghost:
    image: ghost:latest
    ports:
      - "80:2368"
    networks:
      - ghost-net
    volumes:
      - ghost-data:/var/lib/ghost

  postgreql:
    image: postgres:9.6.3
    environment:
      POSTGRES_DB: veryaustinwriting
      POSTGRES_USER: /run/secrets/pg_user
      POSTGRES_PASSWORD: /run/secrets/pg_password
    networks:
      - ghost-net
    volumes: 
      - pg-data:/var/lib/postgresql/data
    secrets:
    - pg_user
    - pg_password


volumes:
  ghost-data:
  pg-data:

networks:
  ghost-net:

networks:
    ghost-net:

secrets:
  pg_user: 
    file: ./secrets/pg_user_secret.txt
  pg_password: 
    file: ./secrets/pg_password_secret.txt
