version: '3.1'

services: 
  ghost:
    image: ghost:latest
    ports:
      - "80:2368"
    volumes:
      - ghost-data:/var/lib/ghost

  postgreql:
    image: postgres:9.6.3
    volumes: 
      - pg-data:/var/lib/postgresql/data

volumes:
  ghost-data:
  pg-data: