version: '3.1'

services:
  ghost:
    build: ./ghost
    image: veryaustin-ghost
    networks:
      - ghost_net
    volumes:
      - ghost_content:/var/lib/ghost
      - ./ghost/config.js:/var/lib/ghost/config.js
volumes:
  ghost_content:

networks:
  ghost_net: